site_name: ONBON Docs
site_url: https://doc.onbonbx.com/
site_author: 'ONBON Team'
site_description: "This is the doc of onbon dev."

# repository addr
repo_url: https://github.com/onbonlab/onbonlab.github.io.git

theme: 
    name: mkdocs
    highlightjs: true
    analytics: {gtag: 'G-274394082'}
    hljs_languages:
        - yaml
        - django

nav:
    - 主页: index.md
    - 全彩播放器系列:
        - 开发指南: zh/y/y.md
        - JAVA: zh/y/java.md
        - C/C++: zh/y/c.md
        - C#: zh/y/csharp.md
        - 开发协议: zh/y/potocol.md
    - 单双色系列:
        - 开发指南: zh/dual/dual.md
        - JAVA: zh/dual/java.md
        - C/C++: zh/dual/c.md
        - C#: zh/y/csharp.md
        - 开发协议: zh/dual/potocol.md
    - 字库系列:
        - 开发指南: zh/k/k.md
        - JAVA: zh/k/java.md
        - C/C++: zh/k/c.md
        - C#: zh/y/csharp.md
        - 开发协议: zh/k/potocol.md
    - 常用工具:
        - 网络抓包: zh/tool/wireshark.md
    - 关于我们 : 'zh/about/about.md'
    
extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - attr_list
    - def_list
  
extra:
  search:
    language: 'jp'

  
# 版权
copyright: "Copyright ? 2020 onbon. All rights reserved. "

plugins:
    - search

